apiVersion: v1
kind: Service
metadata:
  name: corejs-backend
spec:
  selector:
    app: corejs-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 80
  type: ClusterIP
