apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: corejs-prod-ingress
  namespace: corejs-prod
  annotations:
    kubernetes.io/ingress.class: alb

    # ALB public
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # ACM cert
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:130618649638:certificate/c23e55fa-a6b5-4356-909a-30297254c2cb

    # Listen 80 + 443
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

    # Redirect HTTP â†’ HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}

    # Backend is HTTP
    alb.ingress.kubernetes.io/backend-protocol: HTTP

    # Healthcheck
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: '200'

spec:
  ingressClassName: alb
  rules:
  - host: corejs.defenselab.info
    http:
      paths:
      # Redirect all HTTP
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

      # API
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: corejs-backend
            port:
              number: 80

      # Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: corejs-frontend
            port:
              number: 80
