apiVersion: apps/v1
kind: Deployment
metadata:
  name: corejs-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: corejs-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: corejs-frontend
  template:
    metadata:
      labels:
        app: corejs-frontend
    spec:
      containers:
        - name: corejs-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80

