apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: corejs
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
  - host: corejs.defenselab.info
    http:
      paths:
      # Backend: /api/**
      - path: /api/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: corejs-backend
            port:
              number: 80

      # Frontend: còn lại
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: corejs-frontend
            port:
              number: 80
