namespace: corejs

frontend:
  image:
    repository: harbor.defenselab.info/corejs/corejs-frontend
    tag: 0.1.20
  replicaCount: 2
  service:
    port: 80

backend:
  image:
    repository: harbor.defenselab.info/corejs/corejs-backend
    tag: 0.1.20
  replicaCount: 2
  service:
    port: 80

ingress:
  enabled: true
  host: corejs.defenselab.info
