namespace: corejs-prod

frontend:
  image:
    repository: 130618649638.dkr.ecr.ap-southeast-1.amazonaws.com/tuongpx-backend
    tag: 0.1.25
  replicaCount: 0
  service:
    port: 80

backend:
  image:
    repository: 130618649638.dkr.ecr.ap-southeast-1.amazonaws.com/tuongpx-backend
    tag: 0.1.25
  replicaCount: 0
  service:
    port: 80

ingress:
  enabled: true
  host: corejs.defenselab.info
